#!/bin/bash

# DIR SETUP
mkdir -p /var/log/jsgolf
echo "$(date): Setting up folder structure..." >> /var/log/jsgolf/output.txt

export GIT_WORK_TREE=/var/jsgolf
set -x

if [ ! -d $GIT_WORK_TREE ]; then
  sudo mkdir -p $GIT_WORK_TREE
fi

git checkout -f

cd $GIT_WORK_TREE
sudo cp $GIT_WORK_TREE/git-hooks/post-receive /git/hooks/

# Add AWS secret
if [ ! -d ~/.aws ]; then
  mkdir -p ~/.aws
  sudo cp aws-secret ~/.aws/credentials
fi

# NGINX SETUP
echo "$(date): Setting up NGINX..." >> /var/log/jsgolf/output.txt

which nginx
if [ $? != 0 ]; then
  apt-get install -y nginx
fi

# Enable automatic restarting of NGINX if the config changes
if [ ! -d /etc/systemd/system/nginx.service.d ]; then
  mkdir -p /etc/systemd/system/nginx.service.d
  mv restart-nginx.conf /etc/systemd/system/nginx.service.d/override.conf
fi

sudo cp nginx.conf /etc/nginx/nginx.conf

# APP SETUP
echo "$(date): Setting up jsgolf..." >> /var/log/jsgolf/output.txt

which npm
if [ $? != 0 ]; then
  sudo apt install -y npm
  sudo npm install -g npm@latest
fi

sudo npm install
npx gulp

which pm2
if [ $? != 0 ]; then
  npm install -g pm2
  pm2 start app.js
fi

pm2 restart app


