language: node_js
node_js: "6.2.2"
before_install:
    - export DEBUG=true
install:
    - npm install
script:
    - npm test
after_success:
    - git remote add deploy ssh://root@jsgolf.xyz/var/repo/jsgolf.git
    - git push deploy
addons:
  ssh_known_hosts:
      - jsgolf.xyz
