language: node_js
node_js:
- 10.17
env:
  global:
  - secure: PtvNPiJ92VNgt3wFpg9lVXnZVk24jVzwx3gPMhfKfriWnURbtlLbST8tjt9fnZyElQR9vSizNSxV7prvJymG2vAXfGGkXKphqc7SFKS8YkW33MMNl8oYayaCsANj3qwVOAUPKv+gKATzxeru7vNlI3GSJndZjf9iVdshJyQNBUlhK9ospE7ugayB3QDixxNV8EbrvIMG9Zxwaypr/Q82/pGlqqMmE/S9FSUJwbYkxv2tfjaWJk/t/Zj51yePoRDG8BxuL1aSUUO0JC8ejnmWMAxSz6PH61eu0tcUiJMphcOgqvwmHU076F6VUIy4xszViykK5VQfYNFEzBIVtcaMcHuY4y2Ryv4kwm7pBP39P3y3HF1T5ozyFhieM5KR1+qw5ZNLKFN2zqZbFw1RxBr6L0/iRtviV+yMiKTwv1+KxCZBBHN0Al4/TvS5c4ROG8fSDKmnK4iz7Gxb7reORG8MjGTVTnZoZFNF96cOzhwDmKuH6saE3JBr2Rmeg6h8Sefyl7P+zAXyO7NC3wa7SobQEAwhVDGNkWFpbTvE/U4eTr+d9n8rf2qraqxjGGLCY5sxa9cX9bEyF9IzNSXkazKGM/ulC2KMNJuju+cbjn1BanaOmbgNu3cxjA7Pu0ZfoN8ZeMbHsh4ClJGYvE8BVQ+U1koIPILaDXhRHkG0B6vtUtA=
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - jsgolf.xyz
before_install:
- openssl aes-256-cbc -K $encrypted_833934672973_key -iv $encrypted_833934672973_iv -in secrets.tar.enc -out secrets.tar -d
- echo $SECRET > website/secret
install:
- tar xvf secrets.tar
- cd website
- npm install
- npx gulp
before_deploy:
- mv travis_ci /tmp/travis_ci
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis_ci
- ssh-add /tmp/travis_ci
deploy:
  provider: script
  skip_cleanup: true
  script: deploy.sh
  on:
    branch: master
