language: node_js
node_js: "6.2.2"
before_install:
    - openssl aes-256-cbc -K $encrypted_9f9aee1807b3_key -iv $encrypted_9f9aee1807b3_iv -in travis.enc -out ./travis -d
    - export NODE_ENV='debug'
install:
    - npm install
script:
    - npm test
after_success:
    - eval "$(ssh-agent -s)"
    - chmod 600 ./travis
    - ssh-add ./travis
    - git remote add deploy ssh://root@jsgolf.xyz/var/repo/jsgolf.git
    - git push deploy
addons:
  ssh_known_hosts:
      - jsgolf.xyz
