language: node_js
node_js: 9.0.0
before_install:
- openssl aes-256-cbc -K $encrypted_833934672973_key -iv $encrypted_833934672973_iv -in travis_ci.pub.enc -out travis_ci.pub -d
- export DEBUG=true
install:
- npm install
script:
- npm test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 ./travis_key
- ssh-add ./travis_key
- git remote add deploy ssh://root@jsgolf.xyz/var/repo/jsgolf.git
- git push deploy
addons:
  ssh_known_hosts:
  - jsgolf.xyz
