version: 0.2

env:
  parameter-store: 
    SECRET: "jsgolf-secret"

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo $SECRET > secret
      - npm test
      - npx gulp
  build:
    commands:
      - mkdir target
      - mv * target      
      - tar -czf target.tar.gz target

artifacts:
  files:
    - target.tar.gz
