version: 0.2

env:
  parameter-store: 
    SECRET: "jsgolf-secret"

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo $SECRET > secret
      - npm test
      - npx gulp
  build:
    commands:
      - mkdir target
      - mv appspec.yml target
      - mv package.json target
      - mv client node_modules public server target
      - mv index.html target
      - mv robots.txt target
      - mv secret target
      - tar -czf target.tar.gz target

artifacts:
  files:
    - target.tar.gz
