version: 0.2
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/eb-nodejs-6.10.0-amazonlinux-64:4.0.0
  Timeout: 10
env:
  parameter-store:
    SECRET: jsgolf-secret
phases:
  install:
      commands:
      - npm install
  pre_build:
    commands:
      - echo $SECRET > secret
      - npm test      
      - npx gulp
  build:
    commands:
      - mkdir target
      - touch jsgolf-info.log
      - touch jsgolf-error.log
      - mv node_modules target
      - mv api client exercises public utils target
      - mv jsgolf-info.log jsgolf-error.log secret app.js gulpfile.js index.html robots.txt setup_nginx.sh target
artifacts:
  base-directory: target
  files:
    - ./**/*  

