Description: "Autoscaling Group"

Resources:
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        -
          PolicyName: "jsgolf-instance-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: 
                  - "s3:Get*"
                  - "s3:List*"
                  - "dynamodb:*"
                Resource: "*"
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        -
          Ref: "InstanceRole"       
  LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      AssociatePublicIpAddress: "true"
      IamInstanceProfile:
        Ref: InstanceProfile
      InstanceMonitoring: "false"
      InstanceType: "t2.micro"
      KeyName: "jsgolf-key-pair.pem"
      SpotPrice: "0.006"
      ImageId: "ami-4c457735" # CentOS 7
      UserData:
        Fn::Base64: !Sub |
          - "#!/bin/bash -xe\n"
          - "INSTANCE_ID=$(ec2metadata --instance-id)\n"
          - "ALLOCATION_ID=$(aws ec2 describe-tags --region eu-west-1 --filters \"Name=resource-id,Values=$INSTANCE_ID\" \"Name=key,Values=AllocationId\" --output text | awk '{print $5}')\n"
          - "aws ec2 associate-address --region eu-west-1 --allocation-id $ALLOCATION_ID --instance-id $INSTANCE_ID\n"
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    DependsOn: 
      - "LaunchConfiguration"
      - "Address"
    Properties:
      AutoScalingGroupName: "jsgolf-autoscaling-group"
      DesiredCapacity: 1
      LaunchConfiguration: 
        Ref: "LaunchConfiguration"
      MaxSize: 1
      MinSize: 1
      Tags:
        - 
          Key: "Name"
          Value: "jsgolf"
        -
          Key: "AllocationId"
          Value:
            Fn::GetAtt:
              - Address
              - AllocationId
          PropagateAtLaunch: "true"
  Address:
    Type: "AWS::EC2::EIP"


